### PR TITLE
enhance: store `api_key` as `Cow<'static, str>`

### LINKED ISSUE #1: store api_key as `String`, remove the &'static borrow ref
For example a user may want to read their `token` from a configuration file,

it's dirty to call `String::leak` to make it *just works*

### PR DESCRIPTION
**Pull request by mokurin000**
close #1 

with `api_key: impl Into<Cow<'static, str>>`, we could accept various type of a string, provide a more flexible API while avoid unneeded copy

### CODE REVIEW

**Comment by Deaths-Door** [comment]
Instead of `api_key: impl Into<Cow<'static, str>>`  , should it be

**Comment by Deaths-Door** [comment]
Instead of `api_key: impl Into<Cow<'static, str>>` shouldn't it be `api_key: Cow<'a, str>`  , which avoids a new `Box::new` and enchance it even more , to allow users to store `'a` strings instead of `'static`

**Comment by Deaths-Door** [comment]
Instead of `api_key: impl Into<Cow<'static, str>>` shouldn't it be `api_key: Cow<'a, str>` , which avoids a new `Box::new` and enchance it even more , to allow users to store 'a strings instead of `'static`.

*Note* : Sorry for all these notifications , I am trying to figure this part of github out😅

**Comment by mokurin000** [comment]
> which avoids a new `Box::new` and enchance it even more , to allow users to store 'a strings instead of `'static`.

Why is a new `Box::new` needed here?
If the user input is a `String`, we will wrap it with `Cow::Owned` [^1]
If the user input is a `&'a str`, we just wrap it with `Cow::Borrowed` [^0]
Also we have `T: From<T>`, so types not implemented the standard `From` is not a problem

> Instead of `api_key: impl Into<Cow<'static, str>>` shouldn't it be `api_key: Cow<'a, str>` , 

You're right, I will do so
But define it a `impl Into<Cow<'a, str>>` looks good, too

[^0]: https://doc.rust-lang.org/src/alloc/string.rs.html#2871
[^1]: https://doc.rust-lang.org/src/alloc/string.rs.html#2894

**Comment by Deaths-Door** [comment]
> > which avoids a new `Box::new` and enchance it even more , to allow users to store 'a strings instead of `'static`.
> 
> Why is a new `Box::new` needed here? If the user input is a `String`, we will wrap it with `Cow::Owned` [1](#user-content-fn-1-b21f74bf29dae8e0fd01dba515d6ba42) If the user input is a `&'a str`, we just wrap it with `Cow::Borrowed` [2](#user-content-fn-0-b21f74bf29dae8e0fd01dba515d6ba42) Also we have `T: From<T>`, so types not implemented the standard `From` is not a problem
> 
> > Instead of `api_key: impl Into<Cow<'static, str>>` shouldn't it be `api_key: Cow<'a, str>` ,
> 
> You're right, I will do so But define it a `impl Into<Cow<'a, str>>` looks good, too
> 
> ## Footnotes
> 1. https://doc.rust-lang.org/src/alloc/string.rs.html#2894 [↩](#user-content-fnref-1-b21f74bf29dae8e0fd01dba515d6ba42)
> 2. https://doc.rust-lang.org/src/alloc/string.rs.html#2871 [↩](#user-content-fnref-0-b21f74bf29dae8e0fd01dba515d6ba42)

My bad , i was thinking you mean to store a `impl Into<Cow<..>>` in the struct.

Anyways I have added lifetimes to the default arguments feature in this crate , and then if you do not have anything else to add , I will close and merge this with the main branch , and publish it

**Comment by mokurin000** [comment]
> if you do not have anything else to add , I will close and merge this with the main branch , and publish it

Sure

**Pull request merged**
